var wms_layers = [];


        var lyr_CartoDbPositron_0 = new ol.layer.Tile({
            'title': 'CartoDb Positron',
            'type':'base',
            'opacity': 1.000000,
            
            
            source: new ol.source.XYZ({
            attributions: ' ',
                url: 'http://basemaps.cartocdn.com/light_all/{z}/{x}/{y}.png'
            })
        });
var format_Year_2020_1 = new ol.format.GeoJSON();
var features_Year_2020_1 = format_Year_2020_1.readFeatures(json_Year_2020_1, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_Year_2020_1 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_Year_2020_1.addFeatures(features_Year_2020_1);
var lyr_Year_2020_1 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_Year_2020_1, 
                style: style_Year_2020_1,
                popuplayertitle: 'Year_2020',
                interactive: true,
                title: '<img src="styles/legend/Year_2020_1.png" /> Year_2020'
            });
var format_Year_2021_2 = new ol.format.GeoJSON();
var features_Year_2021_2 = format_Year_2021_2.readFeatures(json_Year_2021_2, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_Year_2021_2 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_Year_2021_2.addFeatures(features_Year_2021_2);
var lyr_Year_2021_2 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_Year_2021_2, 
                style: style_Year_2021_2,
                popuplayertitle: 'Year_2021',
                interactive: true,
                title: '<img src="styles/legend/Year_2021_2.png" /> Year_2021'
            });
var format_Year_2024_3 = new ol.format.GeoJSON();
var features_Year_2024_3 = format_Year_2024_3.readFeatures(json_Year_2024_3, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_Year_2024_3 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_Year_2024_3.addFeatures(features_Year_2024_3);
var lyr_Year_2024_3 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_Year_2024_3, 
                style: style_Year_2024_3,
                popuplayertitle: 'Year_2024',
                interactive: true,
                title: '<img src="styles/legend/Year_2024_3.png" /> Year_2024'
            });
var format_Year_2020_4 = new ol.format.GeoJSON();
var features_Year_2020_4 = format_Year_2020_4.readFeatures(json_Year_2020_4, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_Year_2020_4 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_Year_2020_4.addFeatures(features_Year_2020_4);
var lyr_Year_2020_4 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_Year_2020_4, 
                style: style_Year_2020_4,
                popuplayertitle: 'Year_2020',
                interactive: true,
                title: '<img src="styles/legend/Year_2020_4.png" /> Year_2020'
            });
var format_Year_2022_5 = new ol.format.GeoJSON();
var features_Year_2022_5 = format_Year_2022_5.readFeatures(json_Year_2022_5, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_Year_2022_5 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_Year_2022_5.addFeatures(features_Year_2022_5);
var lyr_Year_2022_5 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_Year_2022_5, 
                style: style_Year_2022_5,
                popuplayertitle: 'Year_2022',
                interactive: true,
                title: '<img src="styles/legend/Year_2022_5.png" /> Year_2022'
            });
var format_Year_2023_6 = new ol.format.GeoJSON();
var features_Year_2023_6 = format_Year_2023_6.readFeatures(json_Year_2023_6, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_Year_2023_6 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_Year_2023_6.addFeatures(features_Year_2023_6);
var lyr_Year_2023_6 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_Year_2023_6, 
                style: style_Year_2023_6,
                popuplayertitle: 'Year_2023',
                interactive: true,
                title: '<img src="styles/legend/Year_2023_6.png" /> Year_2023'
            });
var format_Year_2024_7 = new ol.format.GeoJSON();
var features_Year_2024_7 = format_Year_2024_7.readFeatures(json_Year_2024_7, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_Year_2024_7 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_Year_2024_7.addFeatures(features_Year_2024_7);
var lyr_Year_2024_7 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_Year_2024_7, 
                style: style_Year_2024_7,
                popuplayertitle: 'Year_2024',
                interactive: true,
                title: '<img src="styles/legend/Year_2024_7.png" /> Year_2024'
            });
var group_Other = new ol.layer.Group({
                                layers: [],
                                fold: "open",
                                title: 'Other'});
var group_TwoWheel = new ol.layer.Group({
                                layers: [lyr_Year_2020_4,lyr_Year_2022_5,lyr_Year_2023_6,lyr_Year_2024_7,],
                                fold: "open",
                                title: 'TwoWheel'});
var group_Pedestrian = new ol.layer.Group({
                                layers: [lyr_Year_2024_3,],
                                fold: "open",
                                title: 'Pedestrian'});
var group_Motorcycle = new ol.layer.Group({
                                layers: [lyr_Year_2020_1,lyr_Year_2021_2,],
                                fold: "open",
                                title: 'Motorcycle'});
var group_Car = new ol.layer.Group({
                                layers: [],
                                fold: "open",
                                title: 'Car'});
var group_JaffoEilat = new ol.layer.Group({
                                layers: [],
                                fold: "open",
                                title: 'JaffoEilat'});
var group_BikeAccidentsWithBikelaneMinor = new ol.layer.Group({
                                layers: [],
                                fold: "open",
                                title: 'Bike Accidents With Bikelane Minor'});
var group_BikeAccidentswithbikelaneSevere = new ol.layer.Group({
                                layers: [],
                                fold: "open",
                                title: 'Bike Accidents with bikelane Severe'});
var group_BikeAccidentsWithoutBeforeBikeLaneMinor = new ol.layer.Group({
                                layers: [],
                                fold: "open",
                                title: 'Bike Accidents Without/Before BikeLane Minor'});
var group_BikeAccidentsWithoutBeforeBikeLaneSevere = new ol.layer.Group({
                                layers: [],
                                fold: "open",
                                title: 'Bike Accidents Without/Before BikeLane Severe'});

lyr_CartoDbPositron_0.setVisible(true);lyr_Year_2020_1.setVisible(true);lyr_Year_2021_2.setVisible(true);lyr_Year_2024_3.setVisible(true);lyr_Year_2020_4.setVisible(true);lyr_Year_2022_5.setVisible(true);lyr_Year_2023_6.setVisible(true);lyr_Year_2024_7.setVisible(true);
var layersList = [lyr_CartoDbPositron_0,group_Motorcycle,group_Pedestrian,group_TwoWheel];
lyr_Year_2020_1.set('fieldAliases', {'fid': 'fid', 'ACCIDENT_code_ralbad': 'ACCIDENT_code_ralbad', 'Year': 'Year', 'month': 'month', 'Day of the Week': 'Day of the Week', 'Accident Severity': 'Accident Severity', 'Accident Type': 'Accident Type', 'Time of Day': 'Time of Day', 'Road Type': 'Road Type', 'Intersection Name': 'Intersection Name', 'First Street': 'First Street', 'Second Street': 'Second Street', 'Anchor Coordinates (X)': 'Anchor Coordinates (X)', 'Anchor Coordinates (Y)': 'Anchor Coordinates (Y)', 'Anchor Quality': 'Anchor Quality', 'Total Bus Casualties': 'Total Bus Casualties', 'Total Minibus Casualties': 'Total Minibus Casualties', 'Total Motorcycle and Scooter Casualties': 'Total Motorcycle and Scooter Casualties', 'Total Bicycle Casualtie': 'Total Bicycle Casualtie', 'Total Electric Bicycle Casualties': 'Total Electric Bicycle Casualties', 'Total Other Casualties': 'Total Other Casualties', 'Total Ambulance Casualties': 'Total Ambulance Casualties', 'Total  Supporting/Towing Vehicle Casualties': 'Total  Supporting/Towing Vehicle Casualties', 'Total Pedestrian Casualties': 'Total Pedestrian Casualties', 'Total Tractor Casualties': 'Total Tractor Casualties', 'Total Unknown Casualties': 'Total Unknown Casualties', 'Total Taxi Casualties': 'Total Taxi Casualties', 'Total nonLicence other Casualties': 'Total nonLicence other Casualties', 'Total Electric Scooter Casualties': 'Total Electric Scooter Casualties', 'Total Commercial Vehicle and Truck Casualties': 'Total Commercial Vehicle and Truck Casualties', 'Total work Vehicle Casualties': 'Total work Vehicle Casualties', 'Total Private Vehicle Casualties': 'Total Private Vehicle Casualties', 'Total Casualties': 'Total Casualties', 'accident_type': 'accident_type', });
lyr_Year_2021_2.set('fieldAliases', {'fid': 'fid', 'ACCIDENT_code_ralbad': 'ACCIDENT_code_ralbad', 'Year': 'Year', 'month': 'month', 'Day of the Week': 'Day of the Week', 'Accident Severity': 'Accident Severity', 'Accident Type': 'Accident Type', 'Time of Day': 'Time of Day', 'Road Type': 'Road Type', 'Intersection Name': 'Intersection Name', 'First Street': 'First Street', 'Second Street': 'Second Street', 'Anchor Coordinates (X)': 'Anchor Coordinates (X)', 'Anchor Coordinates (Y)': 'Anchor Coordinates (Y)', 'Anchor Quality': 'Anchor Quality', 'Total Bus Casualties': 'Total Bus Casualties', 'Total Minibus Casualties': 'Total Minibus Casualties', 'Total Motorcycle and Scooter Casualties': 'Total Motorcycle and Scooter Casualties', 'Total Bicycle Casualtie': 'Total Bicycle Casualtie', 'Total Electric Bicycle Casualties': 'Total Electric Bicycle Casualties', 'Total Other Casualties': 'Total Other Casualties', 'Total Ambulance Casualties': 'Total Ambulance Casualties', 'Total  Supporting/Towing Vehicle Casualties': 'Total  Supporting/Towing Vehicle Casualties', 'Total Pedestrian Casualties': 'Total Pedestrian Casualties', 'Total Tractor Casualties': 'Total Tractor Casualties', 'Total Unknown Casualties': 'Total Unknown Casualties', 'Total Taxi Casualties': 'Total Taxi Casualties', 'Total nonLicence other Casualties': 'Total nonLicence other Casualties', 'Total Electric Scooter Casualties': 'Total Electric Scooter Casualties', 'Total Commercial Vehicle and Truck Casualties': 'Total Commercial Vehicle and Truck Casualties', 'Total work Vehicle Casualties': 'Total work Vehicle Casualties', 'Total Private Vehicle Casualties': 'Total Private Vehicle Casualties', 'Total Casualties': 'Total Casualties', 'accident_type': 'accident_type', });
lyr_Year_2024_3.set('fieldAliases', {'fid': 'fid', 'ACCIDENT_code_ralbad': 'ACCIDENT_code_ralbad', 'Year': 'Year', 'month': 'month', 'Day of the Week': 'Day of the Week', 'Accident Severity': 'Accident Severity', 'Accident Type': 'Accident Type', 'Time of Day': 'Time of Day', 'Road Type': 'Road Type', 'Intersection Name': 'Intersection Name', 'First Street': 'First Street', 'Second Street': 'Second Street', 'Anchor Coordinates (X)': 'Anchor Coordinates (X)', 'Anchor Coordinates (Y)': 'Anchor Coordinates (Y)', 'Anchor Quality': 'Anchor Quality', 'Total Bus Casualties': 'Total Bus Casualties', 'Total Minibus Casualties': 'Total Minibus Casualties', 'Total Motorcycle and Scooter Casualties': 'Total Motorcycle and Scooter Casualties', 'Total Bicycle Casualtie': 'Total Bicycle Casualtie', 'Total Electric Bicycle Casualties': 'Total Electric Bicycle Casualties', 'Total Other Casualties': 'Total Other Casualties', 'Total Ambulance Casualties': 'Total Ambulance Casualties', 'Total  Supporting/Towing Vehicle Casualties': 'Total  Supporting/Towing Vehicle Casualties', 'Total Pedestrian Casualties': 'Total Pedestrian Casualties', 'Total Tractor Casualties': 'Total Tractor Casualties', 'Total Unknown Casualties': 'Total Unknown Casualties', 'Total Taxi Casualties': 'Total Taxi Casualties', 'Total nonLicence other Casualties': 'Total nonLicence other Casualties', 'Total Electric Scooter Casualties': 'Total Electric Scooter Casualties', 'Total Commercial Vehicle and Truck Casualties': 'Total Commercial Vehicle and Truck Casualties', 'Total work Vehicle Casualties': 'Total work Vehicle Casualties', 'Total Private Vehicle Casualties': 'Total Private Vehicle Casualties', 'Total Casualties': 'Total Casualties', 'accident_type': 'accident_type', });
lyr_Year_2020_4.set('fieldAliases', {'fid': 'fid', 'ACCIDENT_code_ralbad': 'ACCIDENT_code_ralbad', 'Year': 'Year', 'month': 'month', 'Day of the Week': 'Day of the Week', 'Accident Severity': 'Accident Severity', 'Accident Type': 'Accident Type', 'Time of Day': 'Time of Day', 'Road Type': 'Road Type', 'Intersection Name': 'Intersection Name', 'First Street': 'First Street', 'Second Street': 'Second Street', 'Anchor Coordinates (X)': 'Anchor Coordinates (X)', 'Anchor Coordinates (Y)': 'Anchor Coordinates (Y)', 'Anchor Quality': 'Anchor Quality', 'Total Bus Casualties': 'Total Bus Casualties', 'Total Minibus Casualties': 'Total Minibus Casualties', 'Total Motorcycle and Scooter Casualties': 'Total Motorcycle and Scooter Casualties', 'Total Bicycle Casualtie': 'Total Bicycle Casualtie', 'Total Electric Bicycle Casualties': 'Total Electric Bicycle Casualties', 'Total Other Casualties': 'Total Other Casualties', 'Total Ambulance Casualties': 'Total Ambulance Casualties', 'Total  Supporting/Towing Vehicle Casualties': 'Total  Supporting/Towing Vehicle Casualties', 'Total Pedestrian Casualties': 'Total Pedestrian Casualties', 'Total Tractor Casualties': 'Total Tractor Casualties', 'Total Unknown Casualties': 'Total Unknown Casualties', 'Total Taxi Casualties': 'Total Taxi Casualties', 'Total nonLicence other Casualties': 'Total nonLicence other Casualties', 'Total Electric Scooter Casualties': 'Total Electric Scooter Casualties', 'Total Commercial Vehicle and Truck Casualties': 'Total Commercial Vehicle and Truck Casualties', 'Total work Vehicle Casualties': 'Total work Vehicle Casualties', 'Total Private Vehicle Casualties': 'Total Private Vehicle Casualties', 'Total Casualties': 'Total Casualties', 'accident_type': 'accident_type', });
lyr_Year_2022_5.set('fieldAliases', {'fid': 'fid', 'ACCIDENT_code_ralbad': 'ACCIDENT_code_ralbad', 'Year': 'Year', 'month': 'month', 'Day of the Week': 'Day of the Week', 'Accident Severity': 'Accident Severity', 'Accident Type': 'Accident Type', 'Time of Day': 'Time of Day', 'Road Type': 'Road Type', 'Intersection Name': 'Intersection Name', 'First Street': 'First Street', 'Second Street': 'Second Street', 'Anchor Coordinates (X)': 'Anchor Coordinates (X)', 'Anchor Coordinates (Y)': 'Anchor Coordinates (Y)', 'Anchor Quality': 'Anchor Quality', 'Total Bus Casualties': 'Total Bus Casualties', 'Total Minibus Casualties': 'Total Minibus Casualties', 'Total Motorcycle and Scooter Casualties': 'Total Motorcycle and Scooter Casualties', 'Total Bicycle Casualtie': 'Total Bicycle Casualtie', 'Total Electric Bicycle Casualties': 'Total Electric Bicycle Casualties', 'Total Other Casualties': 'Total Other Casualties', 'Total Ambulance Casualties': 'Total Ambulance Casualties', 'Total  Supporting/Towing Vehicle Casualties': 'Total  Supporting/Towing Vehicle Casualties', 'Total Pedestrian Casualties': 'Total Pedestrian Casualties', 'Total Tractor Casualties': 'Total Tractor Casualties', 'Total Unknown Casualties': 'Total Unknown Casualties', 'Total Taxi Casualties': 'Total Taxi Casualties', 'Total nonLicence other Casualties': 'Total nonLicence other Casualties', 'Total Electric Scooter Casualties': 'Total Electric Scooter Casualties', 'Total Commercial Vehicle and Truck Casualties': 'Total Commercial Vehicle and Truck Casualties', 'Total work Vehicle Casualties': 'Total work Vehicle Casualties', 'Total Private Vehicle Casualties': 'Total Private Vehicle Casualties', 'Total Casualties': 'Total Casualties', 'accident_type': 'accident_type', });
lyr_Year_2023_6.set('fieldAliases', {'fid': 'fid', 'ACCIDENT_code_ralbad': 'ACCIDENT_code_ralbad', 'Year': 'Year', 'month': 'month', 'Day of the Week': 'Day of the Week', 'Accident Severity': 'Accident Severity', 'Accident Type': 'Accident Type', 'Time of Day': 'Time of Day', 'Road Type': 'Road Type', 'Intersection Name': 'Intersection Name', 'First Street': 'First Street', 'Second Street': 'Second Street', 'Anchor Coordinates (X)': 'Anchor Coordinates (X)', 'Anchor Coordinates (Y)': 'Anchor Coordinates (Y)', 'Anchor Quality': 'Anchor Quality', 'Total Bus Casualties': 'Total Bus Casualties', 'Total Minibus Casualties': 'Total Minibus Casualties', 'Total Motorcycle and Scooter Casualties': 'Total Motorcycle and Scooter Casualties', 'Total Bicycle Casualtie': 'Total Bicycle Casualtie', 'Total Electric Bicycle Casualties': 'Total Electric Bicycle Casualties', 'Total Other Casualties': 'Total Other Casualties', 'Total Ambulance Casualties': 'Total Ambulance Casualties', 'Total  Supporting/Towing Vehicle Casualties': 'Total  Supporting/Towing Vehicle Casualties', 'Total Pedestrian Casualties': 'Total Pedestrian Casualties', 'Total Tractor Casualties': 'Total Tractor Casualties', 'Total Unknown Casualties': 'Total Unknown Casualties', 'Total Taxi Casualties': 'Total Taxi Casualties', 'Total nonLicence other Casualties': 'Total nonLicence other Casualties', 'Total Electric Scooter Casualties': 'Total Electric Scooter Casualties', 'Total Commercial Vehicle and Truck Casualties': 'Total Commercial Vehicle and Truck Casualties', 'Total work Vehicle Casualties': 'Total work Vehicle Casualties', 'Total Private Vehicle Casualties': 'Total Private Vehicle Casualties', 'Total Casualties': 'Total Casualties', 'accident_type': 'accident_type', });
lyr_Year_2024_7.set('fieldAliases', {'fid': 'fid', 'ACCIDENT_code_ralbad': 'ACCIDENT_code_ralbad', 'Year': 'Year', 'month': 'month', 'Day of the Week': 'Day of the Week', 'Accident Severity': 'Accident Severity', 'Accident Type': 'Accident Type', 'Time of Day': 'Time of Day', 'Road Type': 'Road Type', 'Intersection Name': 'Intersection Name', 'First Street': 'First Street', 'Second Street': 'Second Street', 'Anchor Coordinates (X)': 'Anchor Coordinates (X)', 'Anchor Coordinates (Y)': 'Anchor Coordinates (Y)', 'Anchor Quality': 'Anchor Quality', 'Total Bus Casualties': 'Total Bus Casualties', 'Total Minibus Casualties': 'Total Minibus Casualties', 'Total Motorcycle and Scooter Casualties': 'Total Motorcycle and Scooter Casualties', 'Total Bicycle Casualtie': 'Total Bicycle Casualtie', 'Total Electric Bicycle Casualties': 'Total Electric Bicycle Casualties', 'Total Other Casualties': 'Total Other Casualties', 'Total Ambulance Casualties': 'Total Ambulance Casualties', 'Total  Supporting/Towing Vehicle Casualties': 'Total  Supporting/Towing Vehicle Casualties', 'Total Pedestrian Casualties': 'Total Pedestrian Casualties', 'Total Tractor Casualties': 'Total Tractor Casualties', 'Total Unknown Casualties': 'Total Unknown Casualties', 'Total Taxi Casualties': 'Total Taxi Casualties', 'Total nonLicence other Casualties': 'Total nonLicence other Casualties', 'Total Electric Scooter Casualties': 'Total Electric Scooter Casualties', 'Total Commercial Vehicle and Truck Casualties': 'Total Commercial Vehicle and Truck Casualties', 'Total work Vehicle Casualties': 'Total work Vehicle Casualties', 'Total Private Vehicle Casualties': 'Total Private Vehicle Casualties', 'Total Casualties': 'Total Casualties', 'accident_type': 'accident_type', });
lyr_Year_2020_1.set('fieldImages', {'fid': '', 'ACCIDENT_code_ralbad': '', 'Year': '', 'month': '', 'Day of the Week': '', 'Accident Severity': '', 'Accident Type': '', 'Time of Day': '', 'Road Type': '', 'Intersection Name': '', 'First Street': '', 'Second Street': '', 'Anchor Coordinates (X)': '', 'Anchor Coordinates (Y)': '', 'Anchor Quality': '', 'Total Bus Casualties': '', 'Total Minibus Casualties': '', 'Total Motorcycle and Scooter Casualties': '', 'Total Bicycle Casualtie': '', 'Total Electric Bicycle Casualties': '', 'Total Other Casualties': '', 'Total Ambulance Casualties': '', 'Total  Supporting/Towing Vehicle Casualties': '', 'Total Pedestrian Casualties': '', 'Total Tractor Casualties': '', 'Total Unknown Casualties': '', 'Total Taxi Casualties': '', 'Total nonLicence other Casualties': '', 'Total Electric Scooter Casualties': '', 'Total Commercial Vehicle and Truck Casualties': '', 'Total work Vehicle Casualties': '', 'Total Private Vehicle Casualties': '', 'Total Casualties': '', 'accident_type': '', });
lyr_Year_2021_2.set('fieldImages', {'fid': '', 'ACCIDENT_code_ralbad': '', 'Year': '', 'month': '', 'Day of the Week': '', 'Accident Severity': '', 'Accident Type': '', 'Time of Day': '', 'Road Type': '', 'Intersection Name': '', 'First Street': '', 'Second Street': '', 'Anchor Coordinates (X)': '', 'Anchor Coordinates (Y)': '', 'Anchor Quality': '', 'Total Bus Casualties': '', 'Total Minibus Casualties': '', 'Total Motorcycle and Scooter Casualties': '', 'Total Bicycle Casualtie': '', 'Total Electric Bicycle Casualties': '', 'Total Other Casualties': '', 'Total Ambulance Casualties': '', 'Total  Supporting/Towing Vehicle Casualties': '', 'Total Pedestrian Casualties': '', 'Total Tractor Casualties': '', 'Total Unknown Casualties': '', 'Total Taxi Casualties': '', 'Total nonLicence other Casualties': '', 'Total Electric Scooter Casualties': '', 'Total Commercial Vehicle and Truck Casualties': '', 'Total work Vehicle Casualties': '', 'Total Private Vehicle Casualties': '', 'Total Casualties': '', 'accident_type': '', });
lyr_Year_2024_3.set('fieldImages', {'fid': '', 'ACCIDENT_code_ralbad': '', 'Year': '', 'month': '', 'Day of the Week': '', 'Accident Severity': '', 'Accident Type': '', 'Time of Day': '', 'Road Type': '', 'Intersection Name': '', 'First Street': '', 'Second Street': '', 'Anchor Coordinates (X)': '', 'Anchor Coordinates (Y)': '', 'Anchor Quality': '', 'Total Bus Casualties': '', 'Total Minibus Casualties': '', 'Total Motorcycle and Scooter Casualties': '', 'Total Bicycle Casualtie': '', 'Total Electric Bicycle Casualties': '', 'Total Other Casualties': '', 'Total Ambulance Casualties': '', 'Total  Supporting/Towing Vehicle Casualties': '', 'Total Pedestrian Casualties': '', 'Total Tractor Casualties': '', 'Total Unknown Casualties': '', 'Total Taxi Casualties': '', 'Total nonLicence other Casualties': '', 'Total Electric Scooter Casualties': '', 'Total Commercial Vehicle and Truck Casualties': '', 'Total work Vehicle Casualties': '', 'Total Private Vehicle Casualties': '', 'Total Casualties': '', 'accident_type': '', });
lyr_Year_2020_4.set('fieldImages', {'fid': '', 'ACCIDENT_code_ralbad': '', 'Year': '', 'month': '', 'Day of the Week': '', 'Accident Severity': '', 'Accident Type': '', 'Time of Day': '', 'Road Type': '', 'Intersection Name': '', 'First Street': '', 'Second Street': '', 'Anchor Coordinates (X)': '', 'Anchor Coordinates (Y)': '', 'Anchor Quality': '', 'Total Bus Casualties': '', 'Total Minibus Casualties': '', 'Total Motorcycle and Scooter Casualties': '', 'Total Bicycle Casualtie': '', 'Total Electric Bicycle Casualties': '', 'Total Other Casualties': '', 'Total Ambulance Casualties': '', 'Total  Supporting/Towing Vehicle Casualties': '', 'Total Pedestrian Casualties': '', 'Total Tractor Casualties': '', 'Total Unknown Casualties': '', 'Total Taxi Casualties': '', 'Total nonLicence other Casualties': '', 'Total Electric Scooter Casualties': '', 'Total Commercial Vehicle and Truck Casualties': '', 'Total work Vehicle Casualties': '', 'Total Private Vehicle Casualties': '', 'Total Casualties': '', 'accident_type': '', });
lyr_Year_2022_5.set('fieldImages', {'fid': '', 'ACCIDENT_code_ralbad': '', 'Year': '', 'month': '', 'Day of the Week': '', 'Accident Severity': '', 'Accident Type': '', 'Time of Day': '', 'Road Type': '', 'Intersection Name': '', 'First Street': '', 'Second Street': '', 'Anchor Coordinates (X)': '', 'Anchor Coordinates (Y)': '', 'Anchor Quality': '', 'Total Bus Casualties': '', 'Total Minibus Casualties': '', 'Total Motorcycle and Scooter Casualties': '', 'Total Bicycle Casualtie': '', 'Total Electric Bicycle Casualties': '', 'Total Other Casualties': '', 'Total Ambulance Casualties': '', 'Total  Supporting/Towing Vehicle Casualties': '', 'Total Pedestrian Casualties': '', 'Total Tractor Casualties': '', 'Total Unknown Casualties': '', 'Total Taxi Casualties': '', 'Total nonLicence other Casualties': '', 'Total Electric Scooter Casualties': '', 'Total Commercial Vehicle and Truck Casualties': '', 'Total work Vehicle Casualties': '', 'Total Private Vehicle Casualties': '', 'Total Casualties': '', 'accident_type': '', });
lyr_Year_2023_6.set('fieldImages', {'fid': '', 'ACCIDENT_code_ralbad': '', 'Year': '', 'month': '', 'Day of the Week': '', 'Accident Severity': '', 'Accident Type': '', 'Time of Day': '', 'Road Type': '', 'Intersection Name': '', 'First Street': '', 'Second Street': '', 'Anchor Coordinates (X)': '', 'Anchor Coordinates (Y)': '', 'Anchor Quality': '', 'Total Bus Casualties': '', 'Total Minibus Casualties': '', 'Total Motorcycle and Scooter Casualties': '', 'Total Bicycle Casualtie': '', 'Total Electric Bicycle Casualties': '', 'Total Other Casualties': '', 'Total Ambulance Casualties': '', 'Total  Supporting/Towing Vehicle Casualties': '', 'Total Pedestrian Casualties': '', 'Total Tractor Casualties': '', 'Total Unknown Casualties': '', 'Total Taxi Casualties': '', 'Total nonLicence other Casualties': '', 'Total Electric Scooter Casualties': '', 'Total Commercial Vehicle and Truck Casualties': '', 'Total work Vehicle Casualties': '', 'Total Private Vehicle Casualties': '', 'Total Casualties': '', 'accident_type': '', });
lyr_Year_2024_7.set('fieldImages', {'fid': '', 'ACCIDENT_code_ralbad': '', 'Year': '', 'month': '', 'Day of the Week': '', 'Accident Severity': '', 'Accident Type': '', 'Time of Day': '', 'Road Type': '', 'Intersection Name': '', 'First Street': '', 'Second Street': '', 'Anchor Coordinates (X)': '', 'Anchor Coordinates (Y)': '', 'Anchor Quality': '', 'Total Bus Casualties': '', 'Total Minibus Casualties': '', 'Total Motorcycle and Scooter Casualties': '', 'Total Bicycle Casualtie': '', 'Total Electric Bicycle Casualties': '', 'Total Other Casualties': '', 'Total Ambulance Casualties': '', 'Total  Supporting/Towing Vehicle Casualties': '', 'Total Pedestrian Casualties': '', 'Total Tractor Casualties': '', 'Total Unknown Casualties': '', 'Total Taxi Casualties': '', 'Total nonLicence other Casualties': '', 'Total Electric Scooter Casualties': '', 'Total Commercial Vehicle and Truck Casualties': '', 'Total work Vehicle Casualties': '', 'Total Private Vehicle Casualties': '', 'Total Casualties': '', 'accident_type': '', });
lyr_Year_2020_1.set('fieldLabels', {'fid': 'hidden field', 'ACCIDENT_code_ralbad': 'no label', 'Year': 'inline label - always visible', 'month': 'inline label - always visible', 'Day of the Week': 'inline label - always visible', 'Accident Severity': 'inline label - always visible', 'Accident Type': 'inline label - always visible', 'Time of Day': 'inline label - always visible', 'Road Type': 'inline label - always visible', 'Intersection Name': 'hidden field', 'First Street': 'hidden field', 'Second Street': 'hidden field', 'Anchor Coordinates (X)': 'hidden field', 'Anchor Coordinates (Y)': 'hidden field', 'Anchor Quality': 'hidden field', 'Total Bus Casualties': 'inline label - visible with data', 'Total Minibus Casualties': 'inline label - visible with data', 'Total Motorcycle and Scooter Casualties': 'inline label - visible with data', 'Total Bicycle Casualtie': 'inline label - visible with data', 'Total Electric Bicycle Casualties': 'inline label - visible with data', 'Total Other Casualties': 'inline label - visible with data', 'Total Ambulance Casualties': 'inline label - visible with data', 'Total  Supporting/Towing Vehicle Casualties': 'inline label - visible with data', 'Total Pedestrian Casualties': 'inline label - visible with data', 'Total Tractor Casualties': 'inline label - visible with data', 'Total Unknown Casualties': 'inline label - visible with data', 'Total Taxi Casualties': 'inline label - visible with data', 'Total nonLicence other Casualties': 'inline label - visible with data', 'Total Electric Scooter Casualties': 'inline label - visible with data', 'Total Commercial Vehicle and Truck Casualties': 'inline label - visible with data', 'Total work Vehicle Casualties': 'inline label - visible with data', 'Total Private Vehicle Casualties': 'inline label - visible with data', 'Total Casualties': 'inline label - visible with data', 'accident_type': 'inline label - visible with data', });
lyr_Year_2021_2.set('fieldLabels', {'fid': 'hidden field', 'ACCIDENT_code_ralbad': 'no label', 'Year': 'inline label - always visible', 'month': 'inline label - always visible', 'Day of the Week': 'inline label - always visible', 'Accident Severity': 'inline label - always visible', 'Accident Type': 'inline label - always visible', 'Time of Day': 'inline label - always visible', 'Road Type': 'inline label - always visible', 'Intersection Name': 'hidden field', 'First Street': 'hidden field', 'Second Street': 'hidden field', 'Anchor Coordinates (X)': 'hidden field', 'Anchor Coordinates (Y)': 'hidden field', 'Anchor Quality': 'hidden field', 'Total Bus Casualties': 'inline label - visible with data', 'Total Minibus Casualties': 'inline label - visible with data', 'Total Motorcycle and Scooter Casualties': 'inline label - visible with data', 'Total Bicycle Casualtie': 'inline label - visible with data', 'Total Electric Bicycle Casualties': 'inline label - visible with data', 'Total Other Casualties': 'inline label - visible with data', 'Total Ambulance Casualties': 'inline label - visible with data', 'Total  Supporting/Towing Vehicle Casualties': 'inline label - visible with data', 'Total Pedestrian Casualties': 'inline label - visible with data', 'Total Tractor Casualties': 'inline label - visible with data', 'Total Unknown Casualties': 'inline label - visible with data', 'Total Taxi Casualties': 'inline label - visible with data', 'Total nonLicence other Casualties': 'inline label - visible with data', 'Total Electric Scooter Casualties': 'inline label - visible with data', 'Total Commercial Vehicle and Truck Casualties': 'inline label - visible with data', 'Total work Vehicle Casualties': 'inline label - visible with data', 'Total Private Vehicle Casualties': 'inline label - visible with data', 'Total Casualties': 'inline label - visible with data', 'accident_type': 'inline label - visible with data', });
lyr_Year_2024_3.set('fieldLabels', {'fid': 'hidden field', 'ACCIDENT_code_ralbad': 'no label', 'Year': 'inline label - always visible', 'month': 'inline label - always visible', 'Day of the Week': 'inline label - always visible', 'Accident Severity': 'inline label - always visible', 'Accident Type': 'inline label - always visible', 'Time of Day': 'inline label - always visible', 'Road Type': 'inline label - always visible', 'Intersection Name': 'hidden field', 'First Street': 'hidden field', 'Second Street': 'hidden field', 'Anchor Coordinates (X)': 'hidden field', 'Anchor Coordinates (Y)': 'hidden field', 'Anchor Quality': 'hidden field', 'Total Bus Casualties': 'inline label - visible with data', 'Total Minibus Casualties': 'inline label - visible with data', 'Total Motorcycle and Scooter Casualties': 'inline label - visible with data', 'Total Bicycle Casualtie': 'inline label - visible with data', 'Total Electric Bicycle Casualties': 'inline label - visible with data', 'Total Other Casualties': 'inline label - visible with data', 'Total Ambulance Casualties': 'inline label - visible with data', 'Total  Supporting/Towing Vehicle Casualties': 'inline label - visible with data', 'Total Pedestrian Casualties': 'inline label - visible with data', 'Total Tractor Casualties': 'inline label - visible with data', 'Total Unknown Casualties': 'inline label - visible with data', 'Total Taxi Casualties': 'inline label - visible with data', 'Total nonLicence other Casualties': 'inline label - visible with data', 'Total Electric Scooter Casualties': 'inline label - visible with data', 'Total Commercial Vehicle and Truck Casualties': 'inline label - visible with data', 'Total work Vehicle Casualties': 'inline label - visible with data', 'Total Private Vehicle Casualties': 'inline label - visible with data', 'Total Casualties': 'inline label - visible with data', 'accident_type': 'inline label - visible with data', });
lyr_Year_2020_4.set('fieldLabels', {'fid': 'hidden field', 'ACCIDENT_code_ralbad': 'no label', 'Year': 'inline label - always visible', 'month': 'inline label - always visible', 'Day of the Week': 'inline label - always visible', 'Accident Severity': 'inline label - always visible', 'Accident Type': 'inline label - always visible', 'Time of Day': 'inline label - always visible', 'Road Type': 'inline label - always visible', 'Intersection Name': 'hidden field', 'First Street': 'hidden field', 'Second Street': 'hidden field', 'Anchor Coordinates (X)': 'hidden field', 'Anchor Coordinates (Y)': 'hidden field', 'Anchor Quality': 'hidden field', 'Total Bus Casualties': 'inline label - visible with data', 'Total Minibus Casualties': 'inline label - visible with data', 'Total Motorcycle and Scooter Casualties': 'inline label - visible with data', 'Total Bicycle Casualtie': 'inline label - visible with data', 'Total Electric Bicycle Casualties': 'inline label - visible with data', 'Total Other Casualties': 'inline label - visible with data', 'Total Ambulance Casualties': 'inline label - visible with data', 'Total  Supporting/Towing Vehicle Casualties': 'inline label - visible with data', 'Total Pedestrian Casualties': 'inline label - visible with data', 'Total Tractor Casualties': 'inline label - visible with data', 'Total Unknown Casualties': 'inline label - visible with data', 'Total Taxi Casualties': 'inline label - visible with data', 'Total nonLicence other Casualties': 'inline label - visible with data', 'Total Electric Scooter Casualties': 'inline label - visible with data', 'Total Commercial Vehicle and Truck Casualties': 'inline label - visible with data', 'Total work Vehicle Casualties': 'inline label - visible with data', 'Total Private Vehicle Casualties': 'inline label - visible with data', 'Total Casualties': 'inline label - visible with data', 'accident_type': 'inline label - visible with data', });
lyr_Year_2022_5.set('fieldLabels', {'fid': 'hidden field', 'ACCIDENT_code_ralbad': 'no label', 'Year': 'inline label - always visible', 'month': 'inline label - always visible', 'Day of the Week': 'inline label - always visible', 'Accident Severity': 'inline label - always visible', 'Accident Type': 'inline label - always visible', 'Time of Day': 'inline label - always visible', 'Road Type': 'inline label - always visible', 'Intersection Name': 'hidden field', 'First Street': 'hidden field', 'Second Street': 'hidden field', 'Anchor Coordinates (X)': 'hidden field', 'Anchor Coordinates (Y)': 'hidden field', 'Anchor Quality': 'hidden field', 'Total Bus Casualties': 'inline label - visible with data', 'Total Minibus Casualties': 'inline label - visible with data', 'Total Motorcycle and Scooter Casualties': 'inline label - visible with data', 'Total Bicycle Casualtie': 'inline label - visible with data', 'Total Electric Bicycle Casualties': 'inline label - visible with data', 'Total Other Casualties': 'inline label - visible with data', 'Total Ambulance Casualties': 'inline label - visible with data', 'Total  Supporting/Towing Vehicle Casualties': 'inline label - visible with data', 'Total Pedestrian Casualties': 'inline label - visible with data', 'Total Tractor Casualties': 'inline label - visible with data', 'Total Unknown Casualties': 'inline label - visible with data', 'Total Taxi Casualties': 'inline label - visible with data', 'Total nonLicence other Casualties': 'inline label - visible with data', 'Total Electric Scooter Casualties': 'inline label - visible with data', 'Total Commercial Vehicle and Truck Casualties': 'inline label - visible with data', 'Total work Vehicle Casualties': 'inline label - visible with data', 'Total Private Vehicle Casualties': 'inline label - visible with data', 'Total Casualties': 'inline label - visible with data', 'accident_type': 'inline label - visible with data', });
lyr_Year_2023_6.set('fieldLabels', {'fid': 'hidden field', 'ACCIDENT_code_ralbad': 'no label', 'Year': 'inline label - always visible', 'month': 'inline label - always visible', 'Day of the Week': 'inline label - always visible', 'Accident Severity': 'inline label - always visible', 'Accident Type': 'inline label - always visible', 'Time of Day': 'inline label - always visible', 'Road Type': 'inline label - always visible', 'Intersection Name': 'hidden field', 'First Street': 'hidden field', 'Second Street': 'hidden field', 'Anchor Coordinates (X)': 'hidden field', 'Anchor Coordinates (Y)': 'hidden field', 'Anchor Quality': 'hidden field', 'Total Bus Casualties': 'inline label - visible with data', 'Total Minibus Casualties': 'inline label - visible with data', 'Total Motorcycle and Scooter Casualties': 'inline label - visible with data', 'Total Bicycle Casualtie': 'inline label - visible with data', 'Total Electric Bicycle Casualties': 'inline label - visible with data', 'Total Other Casualties': 'inline label - visible with data', 'Total Ambulance Casualties': 'inline label - visible with data', 'Total  Supporting/Towing Vehicle Casualties': 'inline label - visible with data', 'Total Pedestrian Casualties': 'inline label - visible with data', 'Total Tractor Casualties': 'inline label - visible with data', 'Total Unknown Casualties': 'inline label - visible with data', 'Total Taxi Casualties': 'inline label - visible with data', 'Total nonLicence other Casualties': 'inline label - visible with data', 'Total Electric Scooter Casualties': 'inline label - visible with data', 'Total Commercial Vehicle and Truck Casualties': 'inline label - visible with data', 'Total work Vehicle Casualties': 'inline label - visible with data', 'Total Private Vehicle Casualties': 'inline label - visible with data', 'Total Casualties': 'inline label - visible with data', 'accident_type': 'inline label - visible with data', });
lyr_Year_2024_7.set('fieldLabels', {'fid': 'hidden field', 'ACCIDENT_code_ralbad': 'no label', 'Year': 'inline label - always visible', 'month': 'inline label - always visible', 'Day of the Week': 'inline label - always visible', 'Accident Severity': 'inline label - always visible', 'Accident Type': 'inline label - always visible', 'Time of Day': 'inline label - always visible', 'Road Type': 'inline label - always visible', 'Intersection Name': 'hidden field', 'First Street': 'hidden field', 'Second Street': 'hidden field', 'Anchor Coordinates (X)': 'hidden field', 'Anchor Coordinates (Y)': 'hidden field', 'Anchor Quality': 'hidden field', 'Total Bus Casualties': 'inline label - visible with data', 'Total Minibus Casualties': 'inline label - visible with data', 'Total Motorcycle and Scooter Casualties': 'inline label - visible with data', 'Total Bicycle Casualtie': 'inline label - visible with data', 'Total Electric Bicycle Casualties': 'inline label - visible with data', 'Total Other Casualties': 'inline label - visible with data', 'Total Ambulance Casualties': 'inline label - visible with data', 'Total  Supporting/Towing Vehicle Casualties': 'inline label - visible with data', 'Total Pedestrian Casualties': 'inline label - visible with data', 'Total Tractor Casualties': 'inline label - visible with data', 'Total Unknown Casualties': 'inline label - visible with data', 'Total Taxi Casualties': 'inline label - visible with data', 'Total nonLicence other Casualties': 'inline label - visible with data', 'Total Electric Scooter Casualties': 'inline label - visible with data', 'Total Commercial Vehicle and Truck Casualties': 'inline label - visible with data', 'Total work Vehicle Casualties': 'inline label - visible with data', 'Total Private Vehicle Casualties': 'inline label - visible with data', 'Total Casualties': 'inline label - visible with data', 'accident_type': 'inline label - visible with data', });
lyr_Year_2024_7.on('precompose', function(evt) {
    evt.context.globalCompositeOperation = 'normal';
});